### ISSUE TITLE
Rest QA sheet 3203 rows

### ISSUE THREAD

**Issue by adrose** [PennBBL/pncReproc2015Scripts#44]
Hey @rciric should have caught this before the pul request - sorry about that.

It looks like the rest QA appended each new row to the old QA csv, as the new rest QA csv has 3203 rows and row 1603 is a new header. Thanks to @gbaum for catching this

**Comment by adrose** [comment]
Actually I am going to assume this is going to be an issue for nback as well but I haven't checked, I just know your methodology is equivalent

**Comment by rciric** [comment]
Thanks for drawing my attention to this @gbaum @adrose . After looking into the issue, I've determined that the duplication resulted not from an error in the script but from an oversight in the way that the script was run. (I ran the QA code line by line rather than as a single script, and I must have skipped over the lines that would have removed the old QA files.) This was only an issue for rest, and only for the n=1601 data freeze. This has now been corrected on the filesystem.

[closing issue]
